name: tethys-app-installation

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tethys-app-linter
      uses: Aquaveo/tethys-app-linter@v1
  flake:
    runs-on: ubuntu-latest
    name: Flake8
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Run Flake
        uses: py-actions/flake8@v1
        with:
          #ignore: ""
          #exclude: ""
          max-line-length: "120"
          #path: "."
  deployment:
    runs-on: ubuntu-latest
    name: Deployment
    needs: lint
    steps:
    - name: Get Ref
      id: ref
      run: |
        echo ${GITHUB_REF##*/}
        echo ::set-output name=short_ref::${GITHUB_REF##*/}
    - name: Deploy Stage
      id: deploy
      uses: fjogeleit/http-request-action@master
      with:
        method: 'POST'
        url: 'https://tethys-staging.byu.edu/apps/warehouse/install/git/'
        data: '{"url": "https://github.com/${{ github.repository }}.git", "branch": "${{ steps.ref.outputs.short_ref }}"}'
        timeout: 10000
        customHeaders: '{"Authorization": "Token ${{ secrets.TETHYS_BYU_AUTH_TOKEN }}"}'
    - name: Get Installation ID
      id: iid
      run: |
        echo ${{ steps.deploy.outputs.response }}
        echo ::set-output name=IID::${{ steps.deploy.outputs.response }}
    - name: Get Installation Status
      id: status
      uses: msouff/tethys-app-status@v1
      with:
        url: 'https://tethys-staging.byu.edu/apps/warehouse/install/git/status'
        install_id: '${{ steps.iid.outputs.IID }}'
        tethys_auth_token: '${{ secrets.TETHYS_BYU_AUTH_TOKEN }}'
