name: tethys-app-linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run tethys-app-linter
    steps:
    - uses: actions/checkout@v2
      with:
        path: /
    - run: ls
    - run: ls /
