name: tethys-app-linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run tethys-app-linter
    steps:
    - name: Run flake
      uses: tonybajan/flake8-check-action@v1.0.0
      with:
        select: E,W,F  # check for pep8 and pyflakes errors
        maxlinelength: 120
        repotoken: ${{ secrets.GITHUB_TOKEN }}
