name: tethys-app-installation

on: [push]

jobs:
  app-lint:
    runs-on: ubuntu-latest
    name: Tethys App Lint
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tethys-app-linter
      uses: tethysapp/tethys-app-linter@v1
  flake:
    runs-on: ubuntu-latest
    name: Flake8
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run flake
      uses: tonybajan/flake8-check-action@v1.0.0
      with:
        select: E,W,F  # check for pep8 and pyflakes errors
        maxlinelength: 120
        repotoken: ${{ secrets.GITHUB_TOKEN }}
  deployment:
    runs-on: ubuntu-latest
    name: Deployment
    needs: app-lint
    steps:
    - name: Get Variables
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF##*/}
    - name: Deploy Stage
      id: deploy
      uses: fjogeleit/http-request-action@master
      with:
        method: 'POST'
        url: 'https://tethys-staging.byu.edu/apps/app-store/install/git/'
        data: '{"url": "https://github.com/${{ github.repository }}.git", "branch": "${{ steps.vars.outputs.short_ref }}"}'
        timeout: 10000
        customHeaders: '{"Authorization": "Token ${{ secrets.TETHYS_BYU_AUTH_TOKEN }}"}'
    - name: Get Installation ID
      id: iid
      run: |
        echo ${{ steps.deploy.outputs.response }}
        echo ::set-output name=IID::${{ fromJson(steps.deploy.outputs.response).install_id }}
    - name: Get Installation Status
      id: status
      uses: msouff/tethys-app-status@v1
      with:
        url: 'https://tethys-staging.byu.edu/apps/warehouse/install/git/status'
        install_id: '${{ steps.iid.outputs.IID }}'
        tethys_auth_token: '${{ secrets.TETHYS_BYU_AUTH_TOKEN }}'
